#!/bin/bash


source "aux/data"
source "aux/wiki"

if [[ $1 == "-devel" ]];then
    source aux/devs
fi

if [[ $1 == "-build" ]];then
    source aux/pubs
fi


if [[ $1 == "-apigen" ]];then
    packers_apigen
fi

if [[ $1 == "-wikigen" ]];then
    packers_wikigen
fi
