#!/bin/env bash


function kurosh_webpub() {
    
    local path="$(pwd)/pub"
    test -d $path && rm -fr $path
    cd $(pwd)/doc && hugo --destination "$path"
    unset $path
}

function kurosh_webdev() {
    cd "$(pwd)/doc" && hugo server --config ../con/site.yaml --disableFastRender
}